# spring.datasource.url=jdbc:mysql://localhost:3306/fullstack

# spring.datasource.username=root

#spring.jpa.hibernate.ddl-auto=create

spring:
 datasource:
  url: jdbc:mysql://localhost:3306/fullstack
  username: root
  password: root
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: create
   
server:
 port: 7000